#pragma once

#include <filesystem>
#include <optional>
#include <span>
#include <string>
#include <variant>

namespace kf2::config {

enum class SettingId {
    target_fps,
    minimum_smooth_frame_rate,
    smooth_frame_rate,
    corpse_limit,
    gore_effect_limit,
    explosion_decal_limit,
    impact_decal_limit,
    wound_decal_limit,
    blood_splatter_decal_limit,
    blood_pool_decal_limit,
    blood_effect_limit,
    body_wound_decal_lifetime,
    blood_splatter_lifetime,
    blood_pool_lifetime,
    giblet_lifetime,
    gore_lifetime_multiplier,
    persistent_splats_per_frame,
    blood_splatter_decals,
    secondary_blood_effects,
    static_decals,
    dynamic_decals,
    decal_cull_distance_scale,
    dynamic_shadows,
    light_environment_shadows,
    ambient_occlusion,
    bloom,
    distortion,
    drop_particle_distortion,
    high_quality_materials,
    detail_mode,
    max_shadow_resolution,
    max_whole_scene_shadow_resolution,
    shadow_texels_per_pixel,
    fracture_cull_distance_scale,
    corpse_collision_with_dead,
    corpse_collision_with_living,
    corpse_collision_after_sleep,
    particle_lod_bias,
    skeletal_mesh_lod_bias,
    max_draw_distance_scale,
    global_shadow_distance_scale,
    ragdoll_and_gore_on_dead_bodies,
    depth_of_field,
    light_shafts,
    lens_flares,
    radial_blur,
    separate_translucency,
    fractured_damage,
    motion_blur,
    post_process_aa,
    distance_fog,
    filtered_distortion,
    unbatched_decals,
    whole_scene_dominant_shadows,
    conservative_shadow_bounds,
    max_anisotropy,
    post_process_mlaa,
    persistent_splats,
    screen_space_reflections,
    variable_blur_reflections,
    subsurface_scattering,
    light_functions,
    light_cones,
    destruction_lifetime_scale,
    explosion_lights,
    blood_splat_size,
    blood_pool_size,
    persistent_splat_trace_length,
    whole_scene_shadow_cutoff_distance,
    whole_scene_shadow_fade_distance,
    grouped_per_object_shadows,
    grouped_shadow_min_radius,
    grouped_shadow_max_radius,
    grouped_shadow_ramp_up_factor,
    grouped_shadow_ramp_cutoff,
    max_overlapping_lights,
    light_occlusion_queries,
    depth_prepass,
    reflection_downsample_factor,
    image_grain_scale,
    depth_of_field_quality,
    bloom_quality,
    distance_fog_quality,
    volumetric_lighting_mode,
    physx_level,
    physics_async_scene,
    enable_async_scene,
    flex_invisible_frames_before_sleep,
    flex_distance_before_sleep,
    sph_fluid_mipmap,
    flex_rigid_collision_high_level,
    vertical_sync,
    one_frame_thread_lag,
    per_frame_sleep,
    per_frame_yield,
    force_affinity,
    screen_percentage,
    motion_blur_quality,
    compute_bloom,
    compute_depth_of_field,
    compute_motion_blur,
    compute_ssao,
    compute_ssr,
    hbao,
    new_depth_of_field,
    per_object_shadows,
    hardware_shadow_filtering,
    foreground_shadows_on_world,
    min_shadow_resolution,
    shadow_fade_resolution,
    shadow_depth_bias,
    image_reflections,
    image_reflection_shadowing,
    fractured_parts_scale,
    fracture_direct_spawn_chance,
    fracture_radial_spawn_chance,
    downsampled_translucency,
    max_filter_blur_samples,
    motion_blur_static_scale,
    motion_blur_dynamic_scale,
    override_weapon_depth_of_field,
    boolean_preshadows,
    foreground_preshadows,
    max_per_object_shadow_bounds,
    foreground_projection_depth_bias,
    dynamic_lights,
    composite_dynamic_lights,
    secondary_h_lighting,
    directional_lightmaps,
    motion_blur_pause,
    motion_blur_skinning,
    fog_volumes,
    floating_point_render_targets,
    only_stream_in_textures,
    upscale_screen_percentage,
    temporal_aa,
    max_multi_samples,
    shadow_filter_quality_bias,
    min_pre_shadow_resolution,
    pre_shadow_fade_resolution,
    pre_shadow_resolution_factor,
    shadow_fade_exponent,
    shadow_filter_radius,
    per_object_shadow_transition,
    per_scene_shadow_transition,
    branching_pcf_shadows,
    foreground_self_shadowing,
    high_precision_gbuffers,
    tessellation_pixels_per_triangle,
    csm_split_penumbra_scale,
    csm_split_soft_transition_scale,
    csm_split_depth_bias_scale,
    csm_minimum_fov,
    csm_fov_round_factor,
    scene_capture_streaming_multiplier,
    instanced_rendering,
    summed_area_table_compute,
    histogram_techniques,
    apex_destruction_chunk_islands,
    apex_destruction_shape_count,
    apex_destruction_chunk_separation_lod,
    apex_destruction_actor_creates_per_frame,
    apex_destruction_fractures_per_frame,
    apex_destruction_sort_by_benefit,
    apex_clothing_frequency_window,
    apex_clothing_async_cooking,
    apex_clothing_between_substeps,
    apex_clothing_async_fetch,
    disable_dynamic_wakeup,
    dynamic_collision_threshold,
    max_physics_substeps,
    emitter_pool_scale,
    physics_chunk_override_chance,
    physics_chunk_override_enabled,
    fracture_explosion_velocity_scale,
    limit_explosion_chunk_size,
    limit_damage_chunk_size,
    max_explosion_chunk_size,
    max_damage_chunk_size,
    texture_streaming,
    texture_pool_size,
    texture_streaming_memory_margin,
    texture_streaming_hysteresis_limit,
    minimum_texture_resident_mips,
    texture_async_defrag,
    texture_async_reallocation,
    boost_player_textures,
    max_particle_vertex_memory,
    apex_write_buffer_task,
    apex_render_resources_game_thread,
    gore_level,
    rigid_body_gravity_scale,
    fractured_mesh_weapon_damage,
    decal_lifetime,
    background_level_streaming,
    max_occlusion_pixels_fraction,
    max_particle_resize,
    max_particle_resize_warning,
    check_particle_render_size,
    max_tracked_occlusion_increment,
    tracked_occlusion_step_size,
    streaming_pause,
    stop_streaming_limit,
    lightmap_streaming_factor,
    shadowmap_streaming_factor,
    streaming_lightmaps,
    priority_streaming,
    switching_streaming_system,
    dynamic_streaming,
    particle_percentage,
    shell_eject_lifetime,
    spray_actor_lights,
    pilot_lights,
    footstep_sounds,
    kinematic_update_distance_scale,
    always_on_physics,
    override_map_whole_scene_shadow,
    unverified_effect_profile,
};

enum class SettingType { integer, boolean, real };
using SettingValue = std::variant<int, bool, double>;

struct SettingDefinition {
    SettingId id;
    std::filesystem::path relative_path;
    std::wstring section;
    std::wstring key;
    SettingType type;
    double minimum{0};
    double maximum{0};
    bool adaptive_allowed{true};
    std::span<const int> allowed_integers{};
    double editor_step{0};
    bool insert_if_missing{false};
};

[[nodiscard]] const SettingDefinition* find_setting(SettingId id) noexcept;
[[nodiscard]] std::span<const SettingDefinition> all_settings() noexcept;
[[nodiscard]] std::optional<SettingValue> parse_setting_value(
    const SettingDefinition& definition, std::wstring_view text);
[[nodiscard]] std::optional<std::wstring> serialize_setting_value(
    const SettingDefinition& definition, const SettingValue& value);
[[nodiscard]] std::optional<SettingValue> step_setting_value(
    const SettingDefinition& definition, const SettingValue& value,
    int direction);

}  // namespace kf2::config
